(function(){
"use strict";
let items=[],files=[],library=[],pending=null;
const drafts=new Map();
const esc=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bootstrap=()=>window.__tickTockTomeBootstrap||{};
const itemKey=(form)=>form.dataset.todoEdit||'new';
const typeNames={book:'くらしの本',textbook:'まなびの本',paper:'論文'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const tagChecks=(selected=[])=>(bootstrap().tagCategories||[]).map(category=>{const entries=(bootstrap().tags||[]).filter(tag=>tag.categoryId===category.id);return entries.length?`<section class="todo-tag-group"><strong>${esc(category.name)}</strong><div>${entries.map(tag=>`<label class="check-chip"><input type="checkbox" name="tagIds" value="${esc(tag.id)}" ${selected.includes(tag.id)?'checked':''}><span>${esc(tag.name)}</span></label>`).join('')}</div></section>`:'';}).join('')||'<span class="muted">設定画面でタグを追加できます</span>';
const resourceTags=()=>`<option value="">すべてのタグ</option>${(bootstrap().tags||[]).map(tag=>`<option value="${esc(tag.id)}">${esc(tag.categoryName)}｜${esc(tag.name)}</option>`).join('')}`;
const resourceList=(type,selected=[])=>{const entries=type==='file'?files:library.filter(item=>item.itemType===type),name=type==='file'?'managedFileIds':'libraryIds';return entries.map(item=>`<label class="goal-link" data-todo-resource-item data-resource-type="${type}" data-search="${esc(`${item.name||item.title} ${(item.authors||[]).join(' ')}`.toLocaleLowerCase('ja'))}" data-tags="${esc((item.tagIds||[]).join(' '))}"><input type="checkbox" name="${name}" value="${esc(item.id)}" ${selected.includes(item.id)?'checked':''}><span><strong>${esc(item.name||item.title)}</strong><small>${esc(type==='file'?(item.relativePath||''):(item.authors||[]).join(', ')||'著者未入力')}</small></span></label>`).join('')||'<p class="muted">登録済みの項目はありません。</p>';};
const resourceSection=(type,item)=>`<section class="action-resource-section todo-resource-section" data-todo-resource="${type}"><header><div><h4>${type==='file'?'ファイル':typeNames[type]}</h4><small>登録済みから選択できます</small></div><button type="button" class="secondary" ${type==='file'?'data-todo-add-file':`data-todo-add-library="${type}"`}>＋ この場で追加</button></header><div class="todo-resource-tools"><input type="search" data-todo-resource-query placeholder="${type==='file'?'名前・保存場所':'題名・著者'}で検索"><select data-todo-resource-tag>${resourceTags()}</select></div><div class="goal-link-list">${resourceList(type,type==='file'?(item.managedFileIds||[]):(item.libraryIds||[]))}</div></section>`;
const attachmentItems=(item)=>[...(item.managedFileIds||[]).map(id=>({id,name:files.find(file=>file.id===id)?.name||'登録済みファイル'})),...(item.libraryIds||[]).map(id=>({id,name:library.find(entry=>entry.id===id)?.title||'登録済み資料'}))];
const attachmentSummary=(item)=>{const selected=attachmentItems(item);return `<section class="todo-attachment-summary"><header><div><strong>添付ファイル・資料</strong><small>${selected.length}件を選択中</small></div><button type="button" class="secondary" data-todo-attachments>添付を選ぶ →</button></header>${selected.length?`<ul>${selected.map(entry=>`<li>${esc(entry.name)}</li>`).join('')}</ul>`:'<p>添付はありません。</p>'}${(item.managedFileIds||[]).map(id=>`<input type="hidden" name="managedFileIds" value="${esc(id)}">`).join('')}${(item.libraryIds||[]).map(id=>`<input type="hidden" name="libraryIds" value="${esc(id)}">`).join('')}</section>`;};
const fields=(base={})=>{const item={...base,...(drafts.get(base.id||'new')||{})};return `<label><span>名前</span><input name="title" required maxlength="300" value="${esc(item.title||'')}" placeholder="やること"></label><label><span>期限日</span><input type="date" name="dueDate" value="${esc(item.dueDate||today())}"></label><label><span>達成度</span><div class="progress-control"><input type="range" name="progress" min="0" max="99" step="1" value="${Math.min(99,Number(item.progress||0))}"><output>${Math.min(99,Number(item.progress||0))}%</output></div><small>完了は時間割のアクションから記録します。</small></label><fieldset><legend>タグ（複数選択可）</legend><div class="todo-tag-grid">${tagChecks(item.tagIds||[])}</div></fieldset>${attachmentSummary(item)}`;};
const capture=(form)=>{const data=new FormData(form);return{title:data.get('title'),dueDate:data.get('dueDate'),progress:Number(data.get('progress')),tagIds:data.getAll('tagIds'),managedFileIds:data.getAll('managedFileIds'),libraryIds:data.getAll('libraryIds')};};
const refreshResourceFilter=(section)=>{const query=section.querySelector('[data-todo-resource-query]').value.trim().toLocaleLowerCase('ja'),tag=section.querySelector('[data-todo-resource-tag]').value;section.querySelectorAll('[data-todo-resource-item]').forEach(row=>{row.hidden=Boolean((query&&!row.dataset.search.includes(query))||(tag&&!row.dataset.tags.split(' ').includes(tag)));});};
function renderAttachmentDrawer(){document.querySelector('#todoAttachmentDrawer')?.remove();if(!pending)return;const item=pending.draft,host=document.createElement('div');host.id='todoAttachmentDrawer';host.className='drawer-backdrop todo-attachment-backdrop';host.innerHTML=`<aside class="todo-attachment-drawer"><header><div><span>ATTACHMENTS</span><h2>ファイル・資料を選ぶ</h2><p>選択した項目だけがTodoへ添付されます。</p></div><button type="button" data-attachment-close>×</button></header><div class="todo-attachment-drawer-body">${resourceSection('file',item)}${resourceSection('book',item)}${resourceSection('textbook',item)}${resourceSection('paper',item)}</div><footer><button type="button" class="secondary" data-attachment-close>キャンセル</button><button type="button" class="primary" data-attachment-done>選択を反映</button></footer></aside>`;document.body.append(host);}
async function closeAttachmentDrawer(commit){if(commit&&pending)drafts.set(pending.key,pending.draft);pending=null;document.querySelector('#todoAttachmentDrawer')?.remove();if(commit)await window.tickTockTomeReloadView('todo');}
window.TickTockTomeTodo={
 load:async()=>{const [todoResult,fileResult,books,textbooks,papers]=await Promise.all([window.TickTockTomeApi.todos(),window.TickTockTomeApi.files(),window.TickTockTomeApi.library('book'),window.TickTockTomeApi.library('textbook'),window.TickTockTomeApi.library('paper')]);items=todoResult.items;files=fileResult.items.filter(item=>item.sourceType==='managed');library=[...books.items,...textbooks.items,...papers.items];return items;},
 items:()=>items,
 view:()=>`<div class="section-heading"><div><p class="eyebrow">INBOX</p><h1>Todo</h1><p>やることを集め、時間割へ取り込んで実行します</p></div></div><section class="todo-create-card"><header><span>QUICK ADD</span><div><h2>新しいTodo</h2><p>思いついた作業をここへ置いておきましょう。</p></div></header><form data-todo-add>${fields()}<button class="primary">Todoに追加</button></form></section><div class="todo-list">${items.filter(window.tickTockTomeVisibleByTags||(()=>true)).map(item=>`<form class="todo-card" data-todo-edit="${esc(item.id)}" data-revision="${item.revision}">${fields(item)}<div class="todo-card-actions"><button class="secondary">保存</button><button type="button" class="secondary" data-todo-delete="${esc(item.id)}" data-revision="${item.revision}">削除</button></div></form>`).join('')||'<p class="empty-copy">Todoはありません。時間割へ取り込んだTodoは達成度100%で完了になります。</p>'}</div>`,
 acceptLibrary:async(id)=>{if(!pending)return;pending.draft.libraryIds=[...new Set([...(pending.draft.libraryIds||[]),id])];drafts.set(pending.key,pending.draft);pending=null;document.querySelector('#todoAttachmentDrawer')?.remove();await window.TickTockTomeTodo.load();await window.tickTockTomeReloadView('todo');},
};
document.addEventListener('input',event=>{const form=event.target.closest('[data-todo-add],[data-todo-edit]');if(form&&event.target.name==='progress')event.target.nextElementSibling.textContent=event.target.value+'%';const section=event.target.closest('[data-todo-resource]');if(section&&event.target.matches('[data-todo-resource-query]'))refreshResourceFilter(section);});
document.addEventListener('change',event=>{const section=event.target.closest('[data-todo-resource]');if(section&&event.target.matches('[data-todo-resource-tag]'))refreshResourceFilter(section);const item=event.target.closest('[data-todo-resource-item]');if(item&&pending){const input=item.querySelector('input'),key=input.name,ids=new Set(pending.draft[key]||[]);input.checked?ids.add(input.value):ids.delete(input.value);pending.draft[key]=[...ids];}});
document.addEventListener('submit',async event=>{const form=event.target.closest('[data-todo-add],[data-todo-edit]');if(!form)return;event.preventDefault();const value={...capture(form),revision:Number(form.dataset.revision)},old=items.find(item=>item.id===form.dataset.todoEdit);try{if(old)await window.TickTockTomeApi.updateTodo(old.id,value);else await window.TickTockTomeApi.createTodo(value);drafts.delete(itemKey(form));await window.TickTockTomeTodo.load();await window.tickTockTomeReloadView('todo');}catch(error){window.alert(error.message);}});
document.addEventListener('click',async event=>{const attachmentButton=event.target.closest('[data-todo-attachments]');if(attachmentButton){const form=attachmentButton.closest('form');pending={key:itemKey(form),draft:capture(form)};renderAttachmentDrawer();return;}if(event.target.closest('[data-attachment-close]')){await closeAttachmentDrawer(false);return;}if(event.target.closest('[data-attachment-done]')){await closeAttachmentDrawer(true);return;}const deleteButton=event.target.closest('[data-todo-delete]');if(deleteButton){if(!confirm('このTodoを削除しますか？'))return;try{await window.TickTockTomeApi.deleteTodo(deleteButton.dataset.todoDelete,Number(deleteButton.dataset.revision));drafts.delete(deleteButton.dataset.todoDelete);await window.tickTockTomeReloadView('todo');}catch(error){alert(error.message);}return;}const fileButton=event.target.closest('[data-todo-add-file]');if(fileButton){try{if(!pending)throw new Error('添付選択画面を開き直してください。');if(!(bootstrap().fileRoots||[]).some(root=>root.id==='files'))throw new Error('設定で「ファイル」の基準パスを先に設定してください。');const picked=await window.TickTockTomeApi.pickPath('files','file'),result=await window.TickTockTomeApi.referenceFile({rootId:'files',relativePath:picked.relativePath});pending.draft.managedFileIds=[...new Set([...(pending.draft.managedFileIds||[]),result.item.id])];await window.TickTockTomeTodo.load();renderAttachmentDrawer();}catch(error){alert(error.message);}return;}const libraryButton=event.target.closest('[data-todo-add-library]');if(libraryButton){if(!pending)return;window.__tickTockTomeResourceReturn={kind:'todo',itemType:libraryButton.dataset.todoAddLibrary};window.TickTockTomeEditor.openLibrary(libraryButton.dataset.todoAddLibrary);}});
})();
